// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLm74qG_uzGD8yPDcYuQ9dHBaBQVLiNqg',
    appId: '1:191307545346:web:00cb15ea50a9008d31a01b',
    messagingSenderId: '191307545346',
    projectId: 'voter-entries-27',
    authDomain: 'voter-entries-27.firebaseapp.com',
    storageBucket: 'voter-entries-27.firebasestorage.app',
    measurementId: 'G-1B90TQ35SL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdi6-Q-TwUSuk4peyOSETLCa1uGQSMTUM',
    appId: '1:191307545346:android:8f822b76b77411aa31a01b',
    messagingSenderId: '191307545346',
    projectId: 'voter-entries-27',
    storageBucket: 'voter-entries-27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOZMrWngTCmr47C9IWnSlnqxyWW7n7CJU',
    appId: '1:191307545346:ios:629ba6a141abb5e931a01b',
    messagingSenderId: '191307545346',
    projectId: 'voter-entries-27',
    storageBucket: 'voter-entries-27.firebasestorage.app',
    iosBundleId: 'com.example.checkmeasvoter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOZMrWngTCmr47C9IWnSlnqxyWW7n7CJU',
    appId: '1:191307545346:ios:629ba6a141abb5e931a01b',
    messagingSenderId: '191307545346',
    projectId: 'voter-entries-27',
    storageBucket: 'voter-entries-27.firebasestorage.app',
    iosBundleId: 'com.example.checkmeasvoter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLm74qG_uzGD8yPDcYuQ9dHBaBQVLiNqg',
    appId: '1:191307545346:web:cd0e41619ae00c3c31a01b',
    messagingSenderId: '191307545346',
    projectId: 'voter-entries-27',
    authDomain: 'voter-entries-27.firebaseapp.com',
    storageBucket: 'voter-entries-27.firebasestorage.app',
    measurementId: 'G-LX46EPP0P2',
  );
}
